language: c
git:
  submodules: false

os: linux

cache:
  apt: true


matrix:
  include:
    - env: B=style-check
      dist: trusty
      apt:
        packages:
        - astyle
      before_script:
      - astyle --version
      script:
      - scripts/style-checker.sh format
      - git diff --exit-code
